// Shared review plumbing: the blob store, the Google link, and the pure rules the
// review endpoints all have to agree on.
//
// WHY THIS FILE EXISTS. Three endpoints now touch a review record — the submit handler,
// the click redirect, and the follow-up mailer — and if any two of them disagree about
// which store they are talking to, or about what "already handed to Google" means, the
// system reports things that are not so. That is the exact failure this whole change is
// fixing, so it would be a poor time to reintroduce it by copy-paste.
//
// LOCATION IS LOAD-BEARING. Netlify turns each TOP-LEVEL file in netlify/functions into
// its own deployed endpoint. A shared module dropped next to review.js would be published
// as a function called "reviews" that returns a 500 on every request, because it exports
// no handler. Nested one directory down under a name that does not match its directory,
// it is bundled into whoever requires it and is not itself an endpoint.

// The company's Google review page. ONE definition — this string used to live inline in
// review.js, and every new reader was one more chance to paste a slightly different one.
const GOOGLE_REVIEW_URL = "https://g.page/r/CcBkxtEUiFOGEAE/review";

function blobStore(name) {
  const { getStore } = require("@netlify/blobs");
  const siteID = process.env.NETLIFY_SITE_ID || process.env.SITE_ID;
  const token = process.env.NETLIFY_BLOBS_TOKEN || process.env.NETLIFY_API_TOKEN;
  if (siteID && token) {
    return getStore({ name, siteID, token, consistency: "strong" });
  }
  return getStore({ name, consistency: "strong" });
}

function reviewsStore() {
  return blobStore("reviews");
}

// Clicks live in their OWN store, and that is not tidiness — it is the only way the click
// can be recorded at all.
//
// The hand-off to Google is now a plain anchor the customer taps, with the review POST sent
// fire-and-forget alongside it (see the client). That is deliberate: an anchor tap is the
// only navigation iOS treats as user-initiated, so it is the only one that hands off to the
// Google Maps app where the customer is already signed in. But it means THE CLICK CAN ARRIVE
// BEFORE THE REVIEW DOES — same instant, two requests, no ordering guarantee, and the review
// POST is the slower of the two because it waits on NuVizz.
//
// So g.js cannot "load the review and stamp it": half the time there is nothing to load. It
// writes a click record keyed by a ref the CLIENT generated before either request left, and
// the readers join the two afterwards. A click for a review that never lands is a harmless
// orphan; a click dropped because the review had not landed yet would be the same silent
// under-reporting this whole change exists to end.
//
// Separate store rather than a key prefix in `reviews`, because review.js's GET lists the
// reviews store and returns everything in it — click records would arrive at the dashboard
// pretending to be reviews.
function clicksStore() {
  return blobStore("review-clicks");
}

// The path the customer's Google button actually points at: one hop through our own site
// so the click is observed, then a 302 on to Google. See g.js for why.
//
// Root-relative by default — the portal is same-origin, so the page needs no knowledge of
// which domain it is being served from (tracking.davisdelivery.com and the netlify.app
// alias are both live). The follow-up mailer passes an absolute origin, because a link in
// an inbox has no page to be relative to.
const GOOGLE_CLICK_PATH = "/g";

function trackedGoogleUrl(reviewId, origin) {
  const base = origin ? String(origin).replace(/\/+$/, "") : "";
  const id = String(reviewId == null ? "" : reviewId).trim();
  return id
    ? `${base}${GOOGLE_CLICK_PATH}?rid=${encodeURIComponent(id)}`
    : `${base}${GOOGLE_CLICK_PATH}`;
}

// ── THE CLICK REF ────────────────────────────────────────────────────────────
//
// Generated by the BROWSER, before the review is submitted, because the anchor's href has to
// be final at the moment the page renders it — there is no round-trip to wait for.
//
// It is NOT the review's id, and the server never adopts it as one. This endpoint is public
// and unauthenticated: a client-chosen primary key would let anyone overwrite an existing
// review by guessing its id. The ref only ever names a click record, which is worthless to
// forge, and the review keeps its own server-issued id with the ref stored alongside.
const REF_RE = /^[a-z0-9]{8,48}$/;

function validRef(v) {
  return REF_RE.test(String(v == null ? "" : v).trim().toLowerCase());
}

function cleanRef(v) {
  const s = String(v == null ? "" : v).trim().toLowerCase();
  return REF_RE.test(s) ? s : null;
}

// ── SOURCE ATTRIBUTION ───────────────────────────────────────────────────────
//
// Chad: "i want to track where the review came from tracking or delivery emails".
// The link the customer followed carries ?src=..., the page keeps it for the session and
// POSTs it, and it lands here.
//
// An ALLOW-LIST, not a passthrough. This value is customer-controllable — it arrives in a
// URL anyone can edit — and it is rendered on the admin dashboard. An unknown value is
// recorded as "other" rather than stored verbatim, so the dashboard can never be made to
// display arbitrary text and the source column can never quietly grow a long tail of
// typos that look like real categories.
const KNOWN_SOURCES = ["review-email", "track-email", "review-followup", "direct", "other"];

// How a source reads to a human. Kept beside the allow-list so a new source cannot be added
// without someone deciding what it is called in an inbox and on a dashboard.
const SOURCE_LABEL = {
  "review-email": "the delivery email's Rate button",
  "track-email": "the delivery email's Track link",
  "review-followup": "the review follow-up email",
  direct: "the tracking site directly",
  other: "an unrecognised link",
};

function normalizeSource(raw) {
  const s = String(raw == null ? "" : raw).trim().toLowerCase().slice(0, 40);
  if (!s) return "direct";
  return KNOWN_SOURCES.includes(s) ? s : "other";
}

// ── THE CLICK ────────────────────────────────────────────────────────────────
//
// The one thing about the Google hand-off we can actually OBSERVE. We cannot see whether a
// review was posted — that happens on Google, signed in as the customer, with no callback
// to us — so the honest ceiling is "they took the link". Everything downstream must be
// careful to say that and not more.
//
// firstAt is kept separate from lastAt so a customer who clicks twice does not look like
// two customers, and count is kept so an obviously-bot double-fire is visible rather than
// silently averaged away.
function stampClick(prevClick, nowIso, extra) {
  const prev = prevClick && typeof prevClick === "object" ? prevClick : {};
  const count = Number(prev.count || 0);
  return {
    ...prev,
    ...(extra || {}),
    firstAt: prev.firstAt || nowIso,
    lastAt: nowIso,
    count: (Number.isFinite(count) ? count : 0) + 1,
  };
}

// Did this review ever reach the Google page? The only true predicate available, and it is
// answered by the JOIN — a review alone can never say, which is exactly the problem.
function clickedThrough(review, clicksByRef) {
  if (!review) return false;
  const ref = review.clickRef;
  if (!ref) return false;
  const hit = (clicksByRef || {})[ref];
  return !!(hit && hit.firstAt);
}

// Fold the click store into the review rows the dashboards and the follow-up job read, so
// exactly one place knows how the two are related.
function withClicks(reviews, clicksByRef) {
  return (reviews || []).map((r) => {
    const hit = r && r.clickRef ? (clicksByRef || {})[r.clickRef] : null;
    return {
      ...r,
      googleClickAt: (hit && hit.firstAt) || null,
      googleClickLastAt: (hit && hit.lastAt) || null,
      googleClickCount: (hit && hit.count) || 0,
    };
  });
}

// ── FOLLOW-UP ────────────────────────────────────────────────────────────────
//
// Deliberately conservative. This mails REAL CUSTOMERS, and the failure mode of a loose
// rule here is a stranger being nagged about a review they already left. Every clause
// below is a reason NOT to send.
const FOLLOWUP_DELAY_MS = 2 * 60 * 60 * 1000;   // let them finish on their own first
const FOLLOWUP_MAX_AGE_MS = 7 * 24 * 60 * 60 * 1000; // never chase a stale one

// Same shape the dispatch app uses. Not a full RFC validator — the point is to refuse the
// phone numbers customers type into the same "Phone or email" box, not to police TLDs.
function isEmailAddress(v) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v == null ? "" : v).trim());
}

function followupEligible(review, nowMs) {
  if (!review || typeof review !== "object") return false;
  if (Number(review.rating) < 4) return false;          // never chase a complaint
  // NEVER CHASE A REVIEW FROM BEFORE CLICK TRACKING EXISTED. Every record written by the
  // old code has no clickRef, and therefore reports googleClickAt: null — not because the
  // customer did not go to Google, but because nothing was watching. Mailing those people
  // "you have not posted yet" would be this entire bug run backwards: an absence of
  // evidence dressed up as evidence of absence, this time in a stranger's inbox.
  //
  // clickRef is the marker, and it needs no dated constant to maintain: only the new
  // submit path writes one, so the backlog ages out on its own.
  if (!review.clickRef) return false;
  if (review.googleClickAt) return false;               // they already went (joined by withClicks)
  if (review.followupSentAt) return false;              // once, ever
  if (review.followupClaimedAt) return false;           // a send is already in flight
  if (!isEmailAddress(review.contact)) return false;    // nowhere to send it
  const t = Date.parse(review.submittedAt || "");
  if (!Number.isFinite(t)) return false;                // undatable — leave it alone
  const age = nowMs - t;
  if (age < FOLLOWUP_DELAY_MS) return false;            // give them a chance first
  if (age > FOLLOWUP_MAX_AGE_MS) return false;          // too old to be welcome
  return true;
}

module.exports = {
  GOOGLE_REVIEW_URL,
  blobStore,
  clicksStore,
  validRef,
  cleanRef,
  withClicks,
  GOOGLE_CLICK_PATH,
  trackedGoogleUrl,
  reviewsStore,
  KNOWN_SOURCES,
  SOURCE_LABEL,
  normalizeSource,
  stampClick,
  clickedThrough,
  isEmailAddress,
  followupEligible,
  FOLLOWUP_DELAY_MS,
  FOLLOWUP_MAX_AGE_MS,
};
