// Shared review plumbing: the blob store, the Google link, and the pure rules the
// review endpoints all have to agree on.
//
// WHY THIS FILE EXISTS. Three endpoints now touch a review record — the submit handler,
// the click redirect, and the follow-up mailer — and if any two of them disagree about
// which store they are talking to, or about what "already handed to Google" means, the
// system reports things that are not so. That is the exact failure this whole change is
// fixing, so it would be a poor time to reintroduce it by copy-paste.
//
// LOCATION IS LOAD-BEARING. Netlify turns each TOP-LEVEL file in netlify/functions into
// its own deployed endpoint. A shared module dropped next to review.js would be published
// as a function called "reviews" that returns a 500 on every request, because it exports
// no handler. Nested one directory down under a name that does not match its directory,
// it is bundled into whoever requires it and is not itself an endpoint.

// The company's Google review page. ONE definition — this string used to live inline in
// review.js, and every new reader was one more chance to paste a slightly different one.
const GOOGLE_REVIEW_URL = "https://g.page/r/CcBkxtEUiFOGEAE/review";

function blobStore(name) {
  const { getStore } = require("@netlify/blobs");
  const siteID = process.env.NETLIFY_SITE_ID || process.env.SITE_ID;
  const token = process.env.NETLIFY_BLOBS_TOKEN || process.env.NETLIFY_API_TOKEN;
  if (siteID && token) {
    return getStore({ name, siteID, token, consistency: "strong" });
  }
  return getStore({ name, consistency: "strong" });
}

function reviewsStore() {
  return blobStore("reviews");
}

// Clicks live in their OWN store, and that is not tidiness — it is the only way the click
// can be recorded at all.
//
// The hand-off to Google is now a plain anchor the customer taps, with the review POST sent
// fire-and-forget alongside it (see the client). That is deliberate: an anchor tap is the
// only navigation iOS treats as user-initiated, so it is the only one that hands off to the
// Google Maps app where the customer is already signed in. But it means THE CLICK CAN ARRIVE
// BEFORE THE REVIEW DOES — same instant, two requests, no ordering guarantee, and the review
// POST is the slower of the two because it waits on NuVizz.
//
// So g.js cannot "load the review and stamp it": half the time there is nothing to load. It
// writes a click record keyed by a ref the CLIENT generated before either request left, and
// the readers join the two afterwards. A click for a review that never lands is a harmless
// orphan; a click dropped because the review had not landed yet would be the same silent
// under-reporting this whole change exists to end.
//
// Separate store rather than a key prefix in `reviews`, because review.js's GET lists the
// reviews store and returns everything in it — click records would arrive at the dashboard
// pretending to be reviews.
function clicksStore() {
  return blobStore("review-clicks");
}

// The path the customer's Google button actually points at: one hop through our own site
// so the click is observed, then a 302 on to Google. See g.js for why.
//
// Root-relative by default — the portal is same-origin, so the page needs no knowledge of
// which domain it is being served from (tracking.davisdelivery.com and the netlify.app
// alias are both live). The follow-up mailer passes an absolute origin, because a link in
// an inbox has no page to be relative to.
const GOOGLE_CLICK_PATH = "/g";

// src is a PARAMETER, not something callers append. It used to be concatenated on at the
// call site as "...&src=review-followup", which is correct only while the ref is non-empty:
// with no ref this function emits no query string at all, so the concat produced
// "/g&src=review-followup" — no "?", matching no rule in netlify.toml, i.e. a 404 in a real
// customer's inbox. That was unreachable only because of a guard three files away.
function trackedGoogleUrl(reviewId, origin, src) {
  const base = origin ? String(origin).replace(/\/+$/, "") : "";
  const qs = new URLSearchParams();
  const id = String(reviewId == null ? "" : reviewId).trim();
  if (id) qs.set("rid", id);
  if (src) qs.set("src", String(src));
  const q = qs.toString();
  return q ? `${base}${GOOGLE_CLICK_PATH}?${q}` : `${base}${GOOGLE_CLICK_PATH}`;
}

// ── THE CLICK REF ────────────────────────────────────────────────────────────
//
// Generated by the BROWSER, before the review is submitted, because the anchor's href has to
// be final at the moment the page renders it — there is no round-trip to wait for.
//
// It is NOT the review's id, and the server never adopts it as one. This endpoint is public
// and unauthenticated: a client-chosen primary key would let anyone overwrite an existing
// review by guessing its id. The ref only ever names a click record, which is worthless to
// forge, and the review keeps its own server-issued id with the ref stored alongside.
const REF_RE = /^[a-z0-9]{8,48}$/;

function validRef(v) {
  return REF_RE.test(String(v == null ? "" : v).trim().toLowerCase());
}

function cleanRef(v) {
  const s = String(v == null ? "" : v).trim().toLowerCase();
  return REF_RE.test(s) ? s : null;
}

// ── SOURCE ATTRIBUTION ───────────────────────────────────────────────────────
//
// Chad: "i want to track where the review came from tracking or delivery emails".
// The link the customer followed carries ?src=..., the page keeps it for the session and
// POSTs it, and it lands here.
//
// An ALLOW-LIST, not a passthrough. This value is customer-controllable — it arrives in a
// URL anyone can edit — and it is rendered on the admin dashboard. An unknown value is
// recorded as "other" rather than stored verbatim, so the dashboard can never be made to
// display arbitrary text and the source column can never quietly grow a long tail of
// typos that look like real categories.
const KNOWN_SOURCES = ["review-email", "track-email", "review-followup", "owner-thanks", "direct", "other"];

// How a source reads to a human. Kept beside the allow-list so a new source cannot be added
// without someone deciding what it is called in an inbox and on a dashboard.
const SOURCE_LABEL = {
  "review-email": "the delivery email's Rate button",
  "track-email": "the delivery email's Track link",
  "review-followup": "the review follow-up email",
  "owner-thanks": "Chad's own thank-you note",
  direct: "the tracking site directly",
  other: "an unrecognised link",
};

function normalizeSource(raw) {
  const s = String(raw == null ? "" : raw).trim().toLowerCase().slice(0, 40);
  if (!s) return "direct";
  return KNOWN_SOURCES.includes(s) ? s : "other";
}

// ── THE CLICK ────────────────────────────────────────────────────────────────
//
// The one thing about the Google hand-off we can actually OBSERVE. We cannot see whether a
// review was posted — that happens on Google, signed in as the customer, with no callback
// to us — so the honest ceiling is "they took the link". Everything downstream must be
// careful to say that and not more.
//
// firstAt is kept separate from lastAt so a customer who clicks twice does not look like two
// customers.
//
// count is read-modify-write with no compare-and-set, so two clicks landing in the same
// instant can both read 0 and both write 1. It is therefore a LOWER BOUND on clicks, not a
// tally — worth having, not worth trusting to the unit. firstAt, the field everything else
// keys on, is unaffected: either writer sets it to the same truth.
function stampClick(prevClick, nowIso, extra, navigational = true) {
  const prev = prevClick && typeof prevClick === "object" ? prevClick : {};
  const n = (v) => (Number.isFinite(Number(v)) ? Number(v) : 0);
  const next = {
    ...prev,
    ...(extra || {}),
    lastAt: nowIso,
    count: n(prev.count) + 1,
  };
  if (navigational) {
    // Only a request that looks like a real browser navigation may set firstAt, because
    // firstAt is what every reader treats as "this customer went to Google".
    next.firstAt = prev.firstAt || nowIso;
  } else {
    // A probe is remembered, and kept out of the headline number. Deliberately not
    // discarded: a ref that only ever gets probed is worth being able to see.
    next.probeCount = n(prev.probeCount) + 1;
    next.lastProbeAt = nowIso;
    if (prev.firstAt) next.firstAt = prev.firstAt;
  }
  return next;
}

// Did this review ever reach the Google page? The only true predicate available, and it is
// answered by the JOIN — a review alone can never say, which is exactly the problem.
function clickedThrough(review, clicksByRef) {
  if (!review) return false;
  const ref = review.clickRef;
  if (!ref) return false;
  const hit = (clicksByRef || {})[ref];
  return !!(hit && hit.firstAt);
}

// Fold the click store into the review rows the dashboards and the follow-up job read, so
// exactly one place knows how the two are related.
function withClicks(reviews, clicksByRef) {
  return (reviews || []).map((r) => {
    const hit = r && r.clickRef ? (clicksByRef || {})[r.clickRef] : null;
    return {
      ...r,
      googleClickAt: (hit && hit.firstAt) || null,
      googleClickLastAt: (hit && hit.lastAt) || null,
      googleClickCount: (hit && hit.count) || 0,
      // Fetches that did not look like a browser navigation — mail scanners and link
      // preview bots. Surfaced rather than hidden so a suspiciously quiet click-through
      // rate can be told apart from a suspiciously busy one.
      googleClickProbes: (hit && hit.probeCount) || 0,
      // Which link produced the CLICK, which is not always the source that produced the
      // REVIEW: a follow-up email sends them to /g directly, so the review says
      // "review-email" while the click says "review-followup". Surfaced because g.js writes
      // it and, until now, nothing read it — a field stored for a stated purpose it did not
      // actually serve.
      googleClickSource: (hit && hit.source) || null,
    };
  });
}

// ── FOLLOW-UP ────────────────────────────────────────────────────────────────
//
// Deliberately conservative. This mails REAL CUSTOMERS, and the failure mode of a loose
// rule here is a stranger being nagged about a review they already left. Every clause
// below is a reason NOT to send.
const FOLLOWUP_DELAY_MS = 2 * 60 * 60 * 1000;   // let them finish on their own first
const FOLLOWUP_MAX_AGE_MS = 7 * 24 * 60 * 60 * 1000; // never chase a stale one
// How long a claim holds before the record is considered retryable. Long enough that a slow
// send can never be double-mailed; short enough that one bad run does not cost a day.
const FOLLOWUP_CLAIM_TTL_MS = 6 * 60 * 60 * 1000;

// Same shape the dispatch app uses. Not a full RFC validator — the point is to refuse the
// phone numbers customers type into the same "Phone or email" box, not to police TLDs.
function isEmailAddress(v) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v == null ? "" : v).trim());
}

function followupEligible(review, nowMs) {
  if (!review || typeof review !== "object") return false;
  if (Number(review.rating) < 4) return false;          // never chase a complaint
  // NEVER CHASE A REVIEW FROM BEFORE CLICK TRACKING EXISTED. Every record written by the
  // old code has no clickRef, and therefore reports googleClickAt: null — not because the
  // customer did not go to Google, but because nothing was watching. Mailing those people
  // "you have not posted yet" would be this entire bug run backwards: an absence of
  // evidence dressed up as evidence of absence, this time in a stranger's inbox.
  //
  // clickRef is the marker, and it needs no dated constant to maintain: only the new
  // submit path writes one, so the backlog ages out on its own.
  if (!review.clickRef) return false;
  if (review.googleClickAt) return false;               // they already went (joined by withClicks)
  if (review.followupSentAt) return false;              // once, ever
  // A CLAIM EXPIRES; a send does not. The claim is written before the send so a crash
  // mid-flight cannot mail twice — but a permanent claim means any run that dies partway
  // (a timeout, a bad sender address, one Resend outage) silently marks its whole batch
  // un-nudgeable forever, with nothing to show for it but a console line. That is the same
  // failure as the bug being fixed, just with a different victim. After the window, a
  // claimed-but-unsent record becomes eligible again.
  if (review.followupClaimedAt) {
    const claimed = Date.parse(review.followupClaimedAt);
    if (!Number.isFinite(claimed)) return false;        // unparseable: leave it alone
    if (nowMs - claimed < FOLLOWUP_CLAIM_TTL_MS) return false;
  }
  if (!isEmailAddress(review.contact)) return false;    // nowhere to send it
  const t = Date.parse(review.submittedAt || "");
  if (!Number.isFinite(t)) return false;                // undatable — leave it alone
  const age = nowMs - t;
  if (age < FOLLOWUP_DELAY_MS) return false;            // give them a chance first
  if (age > FOLLOWUP_MAX_AGE_MS) return false;          // too old to be welcome
  return true;
}

module.exports = {
  GOOGLE_REVIEW_URL,
  blobStore,
  clicksStore,
  validRef,
  cleanRef,
  withClicks,
  GOOGLE_CLICK_PATH,
  trackedGoogleUrl,
  reviewsStore,
  KNOWN_SOURCES,
  SOURCE_LABEL,
  normalizeSource,
  stampClick,
  clickedThrough,
  isEmailAddress,
  followupEligible,
  FOLLOWUP_DELAY_MS,
  FOLLOWUP_MAX_AGE_MS,
  FOLLOWUP_CLAIM_TTL_MS,
};
