// Shared review plumbing: the blob store, the Google link, and the pure rules the
// review endpoints all have to agree on.
//
// WHY THIS FILE EXISTS. Three endpoints now touch a review record — the submit handler,
// the click redirect, and the follow-up mailer — and if any two of them disagree about
// which store they are talking to, or about what "already handed to Google" means, the
// system reports things that are not so. That is the exact failure this whole change is
// fixing, so it would be a poor time to reintroduce it by copy-paste.
//
// LOCATION IS LOAD-BEARING. Netlify turns each TOP-LEVEL file in netlify/functions into
// its own deployed endpoint. A shared module dropped next to review.js would be published
// as a function called "reviews" that returns a 500 on every request, because it exports
// no handler. Nested one directory down under a name that does not match its directory,
// it is bundled into whoever requires it and is not itself an endpoint.

// The company's Google review page. ONE definition — this string used to live inline in
// review.js, and every new reader was one more chance to paste a slightly different one.
const GOOGLE_REVIEW_URL = "https://g.page/r/CcBkxtEUiFOGEBM/review";

function blobStore(name) {
  const { getStore } = require("@netlify/blobs");
  const siteID = process.env.NETLIFY_SITE_ID || process.env.SITE_ID;
  const token = process.env.NETLIFY_BLOBS_TOKEN || process.env.NETLIFY_API_TOKEN;
  if (siteID && token) {
    return getStore({ name, siteID, token, consistency: "strong" });
  }
  return getStore({ name, consistency: "strong" });
}

function reviewsStore() {
  return blobStore("reviews");
}

// Clicks live in their OWN store, and that is not tidiness — it is the only way the click
// can be recorded at all.
//
// The hand-off to Google is now a plain anchor the customer taps, with the review POST sent
// fire-and-forget alongside it (see the client). That is deliberate: an anchor tap is the
// only navigation iOS treats as user-initiated, so it is the only one that hands off to the
// Google Maps app where the customer is already signed in. But it means THE CLICK CAN ARRIVE
// BEFORE THE REVIEW DOES — same instant, two requests, no ordering guarantee, and the review
// POST is the slower of the two because it waits on NuVizz.
//
// So g.js cannot "load the review and stamp it": half the time there is nothing to load. It
// writes a click record keyed by a ref the CLIENT generated before either request left, and
// the readers join the two afterwards. A click for a review that never lands is a harmless
// orphan; a click dropped because the review had not landed yet would be the same silent
// under-reporting this whole change exists to end.
//
// Separate store rather than a key prefix in `reviews`, because review.js's GET lists the
// reviews store and returns everything in it — click records would arrive at the dashboard
// pretending to be reviews.
function clicksStore() {
  return blobStore("review-clicks");
}

// The path the customer's Google button actually points at: one hop through our own site
// so the click is observed, then a 302 on to Google. See g.js for why.
//
// Root-relative by default — the portal is same-origin, so the page needs no knowledge of
// which domain it is being served from (tracking.davisdelivery.com and the netlify.app
// alias are both live). The follow-up mailer passes an absolute origin, because a link in
// an inbox has no page to be relative to.
const GOOGLE_CLICK_PATH = "/g";

// src is a PARAMETER, not something callers append. It used to be concatenated on at the
// call site as "...&src=review-followup", which is correct only while the ref is non-empty:
// with no ref this function emits no query string at all, so the concat produced
// "/g&src=review-followup" — no "?", matching no rule in netlify.toml, i.e. a 404 in a real
// customer's inbox. That was unreachable only because of a guard three files away.
function trackedGoogleUrl(reviewId, origin, src) {
  const base = origin ? String(origin).replace(/\/+$/, "") : "";
  const qs = new URLSearchParams();
  const id = String(reviewId == null ? "" : reviewId).trim();
  if (id) qs.set("rid", id);
  if (src) qs.set("src", String(src));
  const q = qs.toString();
  return q ? `${base}${GOOGLE_CLICK_PATH}?${q}` : `${base}${GOOGLE_CLICK_PATH}`;
}

// ── THE CLICK REF ────────────────────────────────────────────────────────────
//
// Generated by the BROWSER, before the review is submitted, because the anchor's href has to
// be final at the moment the page renders it — there is no round-trip to wait for.
//
// It is NOT the review's id, and the server never adopts it as one. This endpoint is public
// and unauthenticated: a client-chosen primary key would let anyone overwrite an existing
// review by guessing its id. The ref only ever names a click record, which is worthless to
// forge, and the review keeps its own server-issued id with the ref stored alongside.
const REF_RE = /^[a-z0-9]{8,48}$/;

function validRef(v) {
  return REF_RE.test(String(v == null ? "" : v).trim().toLowerCase());
}

function cleanRef(v) {
  const s = String(v == null ? "" : v).trim().toLowerCase();
  return REF_RE.test(s) ? s : null;
}

// ── SOURCE ATTRIBUTION ───────────────────────────────────────────────────────
//
// Chad: "i want to track where the review came from tracking or delivery emails".
// The link the customer followed carries ?src=..., the page keeps it for the session and
// POSTs it, and it lands here.
//
// An ALLOW-LIST, not a passthrough. This value is customer-controllable — it arrives in a
// URL anyone can edit — and it is rendered on the admin dashboard. An unknown value is
// recorded as "other" rather than stored verbatim, so the dashboard can never be made to
// display arbitrary text and the source column can never quietly grow a long tail of
// typos that look like real categories.
const KNOWN_SOURCES = ["review-email", "track-email", "review-followup", "direct", "other"];

// How a source reads to a human. Kept beside the allow-list so a new source cannot be added
// without someone deciding what it is called in an inbox and on a dashboard.
const SOURCE_LABEL = {
  "review-email": "the delivery email's Rate button",
  "track-email": "the delivery email's Track link",
  "review-followup": "the review follow-up email",
  direct: "the tracking site directly",
  other: "an unrecognised link",
};

function normalizeSource(raw) {
  const s = String(raw == null ? "" : raw).trim().toLowerCase().slice(0, 40);
  if (!s) return "direct";
  return KNOWN_SOURCES.includes(s) ? s : "other";
}

// ── THE CLICK ────────────────────────────────────────────────────────────────
//
// The one thing about the Google hand-off we can actually OBSERVE. We cannot see whether a
// review was posted — that happens on Google, signed in as the customer, with no callback
// to us — so the honest ceiling is "they took the link". Everything downstream must be
// careful to say that and not more.
//
// firstAt is kept separate from lastAt so a customer who clicks twice does not look like two
// customers.
//
// count is read-modify-write with no compare-and-set, so two clicks landing in the same
// instant can both read 0 and both write 1. It is therefore a LOWER BOUND on clicks, not a
// tally — worth having, not worth trusting to the unit. firstAt, the field everything else
// keys on, is unaffected: either writer sets it to the same truth.
// ── WHICH BROWSER DID THE HAND-OFF HAPPEN IN? ────────────────────────────────
//
// Chad: "You currently think it's them not logging in that is stopping them." He was right to
// push. What is PROVEN is that Google's server 302s a signed-out request on our review link
// to accounts.google.com/ServiceLogin — run directly against the live link. What is NOT
// proven, and what was being asserted anyway, is that any actual customer was signed out.
// Most people are signed into Google on a phone.
//
// Three explanations fit "arrived at Google, no review appeared" equally well:
//   1. SIGNED OUT. An email client's in-app webview keeps its own cookie jar, separate from
//      Safari or Chrome, so a customer signed in everywhere else still meets a login page.
//   2. THEY STARTED OVER. Our link carries no rating and no text, so they face five empty
//      stars and an empty box after already doing both on our page. (Confirmed against the
//      posted reviews: the words on Google are not the words from our form.)
//   3. GOOGLE FILTERED IT. The link carries laa=nmx-review-solicitation-ia2 — Google knows
//      it is solicited, and thin-history or bursty reviews get held.
//
// Only (1) predicts that the failures CONCENTRATE in in-app webviews while the successes sit
// in real browsers. That is a distinguishing prediction, and it needs one thing we were not
// recording: what the customer was using. stampClick stored the timestamp, the count, the
// probes and the source — never the client.
//
// A HEURISTIC, AND LABELLED AS ONE. User agents lie, and reading too much into one is the
// exact failure this repo keeps having. So the raw string is kept alongside the verdict:
// a bucket nobody can check against the original is a number that cannot be audited.
//
// THE KEY SIGNATURE is 'ios-inapp'. An iOS WKWebView hosted by another app sends a UA that
// looks like Mobile Safari but omits the trailing "Safari/" token. That is the population the
// signed-out theory says should be failing, and it is exactly the population that arrives by
// tapping a button inside a delivery email.
const CLIENT_MAX = 400;

function clientKind(userAgent) {
  // A NON-STRING IS ABSENT DATA, NOT A BROWSER. String(42) is "42", which matches none of the
  // patterns below and would fall through to "other" — and "other" is a real browser, so it
  // lands in the CONTROL arm and pads it. Garbage silently moving the answer is the precise
  // way a measurement lies while every test stays green.
  if (typeof userAgent !== "string") return "unknown";
  const ua = userAgent.trim();
  if (!ua) return "unknown";
  const has = (re) => re.test(ua);

  // Named in-app browsers first — these self-identify, so no inference is needed.
  if (has(/\bFBAN\/|\bFBAV\/|FB_IAB/)) return "facebook-inapp";
  if (has(/\bInstagram\b/)) return "instagram-inapp";
  if (has(/Outlook-(iOS|Android)/i)) return "outlook-inapp";
  if (has(/\bGSA\//)) return "google-app-inapp";       // the Google app's own webview

  const ios = has(/\((iPhone|iPad|iPod)/);
  const android = has(/\bAndroid\b/);

  // Branded iOS browsers announce themselves, and they are NOT webviews.
  if (ios && has(/\bCriOS\//)) return "chrome-ios";
  if (ios && has(/\bFxiOS\//)) return "firefox-ios";
  if (ios && has(/\bEdgiOS\//)) return "edge-ios";

  // THE ONE THAT MATTERS. Real Mobile Safari ends with a "Safari/<version>" token; a
  // WKWebView embedded in another app does not. Everything above is excluded first so a
  // branded browser can never fall into this bucket.
  if (ios && has(/AppleWebKit/) && !has(/\bSafari\//)) return "ios-inapp";
  if (ios) return "safari-ios";

  // Android's embedded WebView marks itself with "; wv" in the platform token.
  if (android && has(/;\s*wv\b/)) return "android-inapp";
  if (android && has(/\bChrome\//)) return "chrome-android";
  if (android) return "android-other";

  if (has(/\bEdg\//)) return "edge-desktop";
  if (has(/\bChrome\//)) return "chrome-desktop";
  if (has(/\bFirefox\//)) return "firefox-desktop";
  if (has(/\bSafari\//)) return "safari-desktop";
  return "other";
}

// AN EXPLICIT LIST, NOT A NAMING CONVENTION. This started as /-inapp$/ on the bucket name,
// which works only for as long as nobody adds a bucket whose name happens to contain the
// word — and this string decides which ARM of the experiment a customer lands in, so a
// silent misfile moves the answer rather than breaking anything visible. Every kind
// clientKind can return is listed here or in CLIENT_KINDS, and a test fails if a new one is
// added without someone deciding which side of the line it belongs on.
const IN_APP_KINDS = new Set([
  "ios-inapp", "android-inapp", "outlook-inapp",
  "google-app-inapp", "facebook-inapp", "instagram-inapp",
]);

// Every verdict clientKind can produce. The test that enumerates this is the point of it:
// adding a bucket without classifying it is the mistake it exists to catch.
const CLIENT_KINDS = [
  ...IN_APP_KINDS,
  "chrome-ios", "firefox-ios", "edge-ios", "safari-ios",
  "chrome-android", "android-other",
  "edge-desktop", "chrome-desktop", "firefox-desktop", "safari-desktop",
  "other", "unknown",
];

/** PURE. Is this client one whose cookie jar is isolated from the customer's real browser?
 *  The signed-out theory predicts the failures live HERE and nowhere else. */
function isInAppWebview(kind) {
  return IN_APP_KINDS.has(String(kind || ""));
}

function stampClick(prevClick, nowIso, extra, navigational = true) {
  const prev = prevClick && typeof prevClick === "object" ? prevClick : {};
  const n = (v) => (Number.isFinite(Number(v)) ? Number(v) : 0);
  const next = {
    ...prev,
    ...(extra || {}),
    lastAt: nowIso,
    count: n(prev.count) + 1,
  };
  if (navigational) {
    // Only a request that looks like a real browser navigation may set firstAt, because
    // firstAt is what every reader treats as "this customer went to Google".
    next.firstAt = prev.firstAt || nowIso;
  } else {
    // A probe is remembered, and kept out of the headline number. Deliberately not
    // discarded: a ref that only ever gets probed is worth being able to see.
    next.probeCount = n(prev.probeCount) + 1;
    next.lastProbeAt = nowIso;
    if (prev.firstAt) next.firstAt = prev.firstAt;
  }
  return next;
}

// Did this review ever reach the Google page? The only true predicate available, and it is
// answered by the JOIN — a review alone can never say, which is exactly the problem.
function clickedThrough(review, clicksByRef) {
  if (!review) return false;
  const ref = review.clickRef;
  if (!ref) return false;
  const hit = (clicksByRef || {})[ref];
  return !!(hit && hit.firstAt);
}

// Fold the click store into the review rows the dashboards and the follow-up job read, so
// exactly one place knows how the two are related.
function withClicks(reviews, clicksByRef) {
  return (reviews || []).map((r) => {
    const hit = r && r.clickRef ? (clicksByRef || {})[r.clickRef] : null;
    return {
      ...r,
      googleClickAt: (hit && hit.firstAt) || null,
      googleClickLastAt: (hit && hit.lastAt) || null,
      googleClickCount: (hit && hit.count) || 0,
      // Fetches that did not look like a browser navigation — mail scanners and link
      // preview bots. Surfaced rather than hidden so a suspiciously quiet click-through
      // rate can be told apart from a suspiciously busy one.
      googleClickProbes: (hit && hit.probeCount) || 0,
      // Which link produced the CLICK, which is not always the source that produced the
      // REVIEW: a follow-up email sends them to /g directly, so the review says
      // "review-email" while the click says "review-followup". Surfaced because g.js writes
      // it and, until now, nothing read it — a field stored for a stated purpose it did not
      // actually serve.
      googleClickSource: (hit && hit.source) || null,
      // WHAT THEY TAPPED IT IN. The distinguishing signal for "why did half of them not
      // post" — see clientKind. Null on every click recorded before this shipped, which is
      // "we were not looking", not "unknown browser", and the dashboard says so.
      googleClient: (hit && hit.client) || null,
      googleClientUA: (hit && hit.ua) || null,
    };
  });
}

// ── THE ANSWER, WHEN THERE IS ENOUGH OF IT TO BE ONE ─────────────────────────
//
// PURE. Joins what we recorded (which browser they tapped in) to what only Chad can see
// (whether the review appeared on Google) and reports the split.
//
// The signed-out theory predicts one specific shape: the post rate inside in-app webviews
// should be markedly WORSE than in real browsers, because only the webview's cookie jar is
// isolated. If both come out the same, the theory is wrong and the cause is elsewhere —
// Google filtering solicited reviews, or people simply not starting over on a blank form.
//
// IT REFUSES TO CONCLUDE ON THIN DATA, and that refusal is the point. Davis gets one or two
// five-star reviews a day; a 2-of-3 split is noise, and the whole reason this function
// exists is that a plausible story fitted to a small sample is what went wrong the first
// time. `sufficient` is false until both arms have MIN_PER_ARM checked rows, and the caller
// is expected to print the counts and no verdict until then.
const MIN_PER_ARM = 5;

function postRateByClient(reviews) {
  const rows = (reviews || []).filter((r) => r && r.googleClickAt);   // arrived at Google
  const blank = () => ({ arrived: 0, checked: 0, landed: 0, missing: 0 });
  const byClient = {};
  const inApp = blank();
  const browser = blank();
  const unknownClient = blank();

  for (const r of rows) {
    const kind = r.googleClient || null;
    const bucket = byClient[kind || "not-recorded"] || (byClient[kind || "not-recorded"] = blank());
    // A click stamped before the client was recorded is NOT an unknown browser — it is a
    // period when nothing was looking. Kept in its own bucket so it can never be averaged
    // into either arm and quietly move the answer.
    const arm = kind == null ? unknownClient : (isInAppWebview(kind) ? inApp : browser);
    for (const b of [bucket, arm]) {
      b.arrived += 1;
      if (r.postedOnGoogle === true) { b.checked += 1; b.landed += 1; }
      else if (r.postedOnGoogle === false) { b.checked += 1; b.missing += 1; }
    }
  }

  const rate = (b) => (b.checked ? b.landed / b.checked : null);
  const sufficient = inApp.checked >= MIN_PER_ARM && browser.checked >= MIN_PER_ARM;
  return {
    minPerArm: MIN_PER_ARM,
    arrived: rows.length,
    checked: rows.filter((r) => r.postedOnGoogle === true || r.postedOnGoogle === false).length,
    unchecked: rows.filter((r) => r.postedOnGoogle !== true && r.postedOnGoogle !== false).length,
    byClient,
    inApp: { ...inApp, rate: rate(inApp) },
    browser: { ...browser, rate: rate(browser) },
    notRecorded: { ...unknownClient, rate: rate(unknownClient) },
    sufficient,
    // Stated as a comparison, never as a cause. Even with enough rows this says which arm
    // does worse, not why — Google filtering could also concentrate somewhere.
    leans: sufficient
      ? (rate(inApp) < rate(browser) ? "in-app webviews post less often"
        : rate(inApp) > rate(browser) ? "in-app webviews post MORE often — the sign-in theory does not hold"
        : "no difference between in-app and real browsers")
      : null,
  };
}

// ── FOLLOW-UP ────────────────────────────────────────────────────────────────
//
// Deliberately conservative. This mails REAL CUSTOMERS, and the failure mode of a loose
// rule here is a stranger being nagged about a review they already left. Every clause
// below is a reason NOT to send.
const FOLLOWUP_DELAY_MS = 2 * 60 * 60 * 1000;   // let them finish on their own first
const FOLLOWUP_MAX_AGE_MS = 7 * 24 * 60 * 60 * 1000; // never chase a stale one
// How long a claim holds before the record is considered retryable. Long enough that a slow
// send can never be double-mailed; short enough that one bad run does not cost a day.
const FOLLOWUP_CLAIM_TTL_MS = 6 * 60 * 60 * 1000;

// Same shape the dispatch app uses. Not a full RFC validator — the point is to refuse the
// phone numbers customers type into the same "Phone or email" box, not to police TLDs.
function isEmailAddress(v) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v == null ? "" : v).trim());
}

function followupEligible(review, nowMs) {
  if (!review || typeof review !== "object") return false;
  if (Number(review.rating) < 4) return false;          // never chase a complaint
  // NEVER CHASE A REVIEW FROM BEFORE CLICK TRACKING EXISTED. Every record written by the
  // old code has no clickRef, and therefore reports googleClickAt: null — not because the
  // customer did not go to Google, but because nothing was watching. Mailing those people
  // "you have not posted yet" would be this entire bug run backwards: an absence of
  // evidence dressed up as evidence of absence, this time in a stranger's inbox.
  //
  // clickRef is the marker, and it needs no dated constant to maintain: only the new
  // submit path writes one, so the backlog ages out on its own.
  if (!review.clickRef) return false;
  if (review.googleClickAt) return false;               // they already went (joined by withClicks)
  if (review.followupSentAt) return false;              // once, ever
  // A CLAIM EXPIRES; a send does not. The claim is written before the send so a crash
  // mid-flight cannot mail twice — but a permanent claim means any run that dies partway
  // (a timeout, a bad sender address, one Resend outage) silently marks its whole batch
  // un-nudgeable forever, with nothing to show for it but a console line. That is the same
  // failure as the bug being fixed, just with a different victim. After the window, a
  // claimed-but-unsent record becomes eligible again.
  if (review.followupClaimedAt) {
    const claimed = Date.parse(review.followupClaimedAt);
    if (!Number.isFinite(claimed)) return false;        // unparseable: leave it alone
    if (nowMs - claimed < FOLLOWUP_CLAIM_TTL_MS) return false;
  }
  if (!isEmailAddress(review.contact)) return false;    // nowhere to send it
  const t = Date.parse(review.submittedAt || "");
  if (!Number.isFinite(t)) return false;                // undatable — leave it alone
  const age = nowMs - t;
  if (age < FOLLOWUP_DELAY_MS) return false;            // give them a chance first
  if (age > FOLLOWUP_MAX_AGE_MS) return false;          // too old to be welcome
  return true;
}

module.exports = {
  GOOGLE_REVIEW_URL,
  clientKind,
  CLIENT_KINDS,
  IN_APP_KINDS,
  postRateByClient,
  MIN_PER_ARM,
  isInAppWebview,
  CLIENT_MAX,
  blobStore,
  clicksStore,
  validRef,
  cleanRef,
  withClicks,
  GOOGLE_CLICK_PATH,
  trackedGoogleUrl,
  reviewsStore,
  KNOWN_SOURCES,
  SOURCE_LABEL,
  normalizeSource,
  stampClick,
  clickedThrough,
  isEmailAddress,
  followupEligible,
  FOLLOWUP_DELAY_MS,
  FOLLOWUP_MAX_AGE_MS,
  FOLLOWUP_CLAIM_TTL_MS,
};
